#!/bin/bash

set -ex

if [[ -d "docker-entrypoint.d" ]]
then
echo "Running docker-entrypoint.d files"
/bin/run-parts docker-entrypoint.d
fi

function test_nomad {
  curl http://0.0.0.0:4646/v1/status/leader
  echo $?
}
function run_app {
  while [ $(test_nomad) -ne 0 ]
  do
    echo "Waiting for nomad..."
    sleep 2
  done
  nomad job run /app.nomad
  nomad job run /EK.nomad
}

mkdir -p /data/nomad
# su -c 'nomad agent -dev -bind 0.0.0.0 -log-level INFO' nomad &
nomad agent -config /etc/nomad.d/server.hcl -dev-connect -bind 0.0.0.0 -log-level INFO  2>&1 | tee /tmp/nomad_log &
dockerd -p /var/run/docker.pid &
run_app &
chmod -R 755 /data/nomad
wait
# echo "Running $@"
# exec "$@"
