# fly.toml file generated for docker-for-kurt on 2021-06-23T18:04:47-05:00

app = "nomadock"

kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  strategy = "immediate"

[experimental]
  auto_rollback = false

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# rest api and ui
[[services]]
  internal_port = 4646
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 4646

# rpc
[[services]]
  internal_port = 4646
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 4647

# gossip
[[services]]
  internal_port = 4648
  protocol = "udp"

  [[services.ports]]
    port = 4648

#4646 4647 4648 4648/udp
# [[mounts]]
#   destination = "/data"
#   source = "data"
